name: FreeCycle Scraper

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allows you to run manually from GitHub UI
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
     FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run scraper
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SEARCH_ITEMS: ${{ secrets.SEARCH_ITEMS }}
          EMAIL_RECEIVER: ${{secrets.EMAIl_RECEIVER}}
        run: node scrape-script.js